import { useCallback, useEffect, useState } from 'react'
import { Section, SectionHeading, Reveal, Still } from './primitives.jsx'
import { gallery } from '../../config/wedding.config.js'
import { stills } from '../../config/stills.generated.js'

/**
 * Stills lifted straight from the film — the same frames, nothing else.
 * The list is generated by the frame pipeline, so it stays in step with the
 * assets on disk.
 */
export default function Gallery() {
  const [open, setOpen] = useState(-1)
  const count = stills.length

  const close = useCallback(() => setOpen(-1), [])
  const step = useCallback(
    (delta) => setOpen((i) => (i < 0 ? i : (i + delta + count) % count)),
    [count]
  )

  useEffect(() => {
    if (open < 0) return
    const onKey = (e) => {
      if (e.key === 'Escape') close()
      if (e.key === 'ArrowRight') step(1)
      if (e.key === 'ArrowLeft') step(-1)
    }
    document.addEventListener('keydown', onKey)
    document.body.classList.add('is-locked')
    return () => {
      document.removeEventListener('keydown', onKey)
      document.body.classList.remove('is-locked')
    }
  }, [open, close, step])

  if (!count) return null

  return (
    <Section id="gallery" className="section--gallery" label="Gallery">
      <SectionHeading kicker="From the film" title={gallery.heading} intro={gallery.intro} />

      <div className="gallery__grid">
        {stills.map((still, i) => (
          <Reveal
            as="button"
            type="button"
            key={still.name}
            className="gallery__item"
            delay={(i % 4) * 80}
            onClick={() => setOpen(i)}
          >
            <Still src={still.src} alt={still.caption} width="1280" height="720" />
            <span className="gallery__caption">{still.caption}</span>
          </Reveal>
        ))}
      </div>

      {open >= 0 && (
        <div className="lightbox" role="dialog" aria-modal="true" aria-label={stills[open].caption}>
          <button type="button" className="lightbox__backdrop" onClick={close} aria-label="Close" />
          <figure className="lightbox__figure">
            <Still src={stills[open].src} alt={stills[open].caption} width="1280" height="720" />
            <figcaption>{stills[open].caption}</figcaption>
          </figure>
          <button type="button" className="lightbox__nav lightbox__nav--prev" onClick={() => step(-1)} aria-label="Previous">
            ‹
          </button>
          <button type="button" className="lightbox__nav lightbox__nav--next" onClick={() => step(1)} aria-label="Next">
            ›
          </button>
          <button type="button" className="lightbox__close" onClick={close} aria-label="Close">
            ×
          </button>
        </div>
      )}
    </Section>
  )
}
