/**
 * Frame pipeline.
 *
 * Source: "DESKTOP FRAMES/frame 00 (N).png"  (N = 1..300, 1280x720 PNG, ~293 MB)
 *
 * The source is a 24 fps render exported at 30 fps, so every 5th frame is an exact
 * duplicate of the one before it. We drop those (300 -> 240 unique frames), which
 * removes 20% of the payload and yields a perfectly uniform sequence.
 *
 * Emits WebP at two resolutions plus a manifest that maps the original frame
 * numbers (the ones the scene config is authored against) onto output indices.
 *
 *   npm run frames
 */
import sharp from 'sharp'
import { createHash } from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SRC_DIR = path.join(ROOT, 'DESKTOP FRAMES')
const OUT_DIR = path.join(ROOT, 'public', 'frames')
const STILL_DIR = path.join(ROOT, 'public', 'stills')

const SOURCE_COUNT = 300
const srcPath = (n) => path.join(SRC_DIR, `frame 00 (${n}).png`)

const VARIANTS = [
  { key: 'desktop', dir: 'desktop', width: 1280, height: 720, quality: 76 },
  { key: 'mobile', dir: 'mobile', width: 854, height: 480, quality: 70 },
]

/** Full-frame stills reused by the gallery (authored in source frame numbers). */
const STILLS = [
  { name: 'mehndi-mandap', frame: 8, caption: 'The mehndi mandap' },
  { name: 'mehndi-arrival', frame: 34, caption: 'Arrival' },
  { name: 'mehndi-together', frame: 64, caption: 'Mehndi night' },
  { name: 'barat-hall', frame: 104, caption: 'The barat' },
  { name: 'barat-couple', frame: 138, caption: 'Side by side' },
  { name: 'walima-stage', frame: 196, caption: 'Walima' },
  { name: 'walima-couple', frame: 228, caption: 'The reception' },
  { name: 'sofa-final', frame: 288, caption: 'Happily ever after' },
]

/**
 * Portrait crops for the couple section, taken straight from the render.
 * Boxes are 4:5 and measured against source frame 206 (1280x720): the groom
 * occupies x 405-590 and the bride x 690-870, so neither box clips the other
 * person or cuts anybody off.
 */
const PORTRAITS = [
  { name: 'groom', frame: 206, left: 320, top: 0, width: 336, height: 420 },
  { name: 'bride', frame: 206, left: 616, top: 0, width: 336, height: 420 },
]

const sha1 = (buf) => createHash('sha1').update(buf).digest('hex')
const pad = (n) => String(n).padStart(3, '0')

/** `npm run frames -- --stills` re-cuts only the gallery/portrait images. */
const STILLS_ONLY = process.argv.includes('--stills')

async function main() {
  if (!STILLS_ONLY) {
    await fs.rm(OUT_DIR, { recursive: true, force: true })
    for (const v of VARIANTS) await fs.mkdir(path.join(OUT_DIR, v.dir), { recursive: true })
  }
  await fs.mkdir(STILL_DIR, { recursive: true })

  // ---- pass 1: dedupe -------------------------------------------------------
  const kept = []              // kept[outIndex] = source frame number
  const sourceToOut = new Array(SOURCE_COUNT + 1).fill(0)
  let prevHash = null

  for (let n = 1; n <= (STILLS_ONLY ? 1 : SOURCE_COUNT); n++) {
    const hash = sha1(await fs.readFile(srcPath(n)))
    if (hash !== prevHash) {
      kept.push(n)
      prevHash = hash
    }
    sourceToOut[n] = kept.length - 1
  }
  if (!STILLS_ONLY) console.log(`dedupe: ${SOURCE_COUNT} source frames -> ${kept.length} unique frames`)

  // ---- pass 2: encode -------------------------------------------------------
  const bytes = {}
  for (const v of STILLS_ONLY ? [] : VARIANTS) {
    let total = 0
    for (let i = 0; i < kept.length; i++) {
      const out = path.join(OUT_DIR, v.dir, `f${pad(i)}.webp`)
      await sharp(srcPath(kept[i]))
        .resize(v.width, v.height, { fit: 'fill' })
        .webp({ quality: v.quality, effort: 5, smartSubsample: true })
        .toFile(out)
      total += (await fs.stat(out)).size
      if (i % 40 === 0) process.stdout.write(`  ${v.key} ${i}/${kept.length}\r`)
    }
    bytes[v.key] = total
    console.log(`  ${v.key}: ${kept.length} files, ${(total / 1048576).toFixed(1)} MB   `)
  }

  // ---- stills + portraits ---------------------------------------------------
  for (const s of STILLS) {
    await sharp(srcPath(s.frame))
      .resize(1280, 720, { fit: 'fill' })
      .webp({ quality: 80, effort: 6 })
      .toFile(path.join(STILL_DIR, `${s.name}.webp`))
  }
  for (const p of PORTRAITS) {
    await sharp(srcPath(p.frame))
      .extract({ left: p.left, top: p.top, width: p.width, height: p.height })
      .resize(672, 840, { fit: 'fill' })
      .webp({ quality: 84, effort: 6 })
      .toFile(path.join(STILL_DIR, `${p.name}.webp`))
  }
  await fs.writeFile(
    path.join(ROOT, 'src', 'config', 'stills.generated.js'),
    `/* Generated by scripts/build-frames.mjs — do not edit by hand. */\n` +
      `export const stills = ${JSON.stringify(
        STILLS.map((s) => ({ name: s.name, caption: s.caption, src: `/stills/${s.name}.webp` })),
        null,
        2
      )}\n`
  )
  console.log(`stills: ${STILLS.length} gallery + ${PORTRAITS.length} portraits`)
  if (STILLS_ONLY) return

  // ---- low quality image placeholder (instant first paint) ------------------
  const lqipBuf = await sharp(srcPath(kept[0]))
    .resize(32, 18, { fit: 'fill' })
    .blur(1.4)
    .webp({ quality: 40 })
    .toBuffer()
  const lqip = `data:image/webp;base64,${lqipBuf.toString('base64')}`

  // ---- manifest -------------------------------------------------------------
  const manifest = {
    generatedFrom: 'DESKTOP FRAMES/frame 00 (N).png',
    sourceCount: SOURCE_COUNT,
    count: kept.length,
    lqip,
    variants: Object.fromEntries(
      VARIANTS.map((v) => [
        v.key,
        { path: `/frames/${v.dir}`, width: v.width, height: v.height, bytes: bytes[v.key] },
      ])
    ),
    /** sourceToOut[sourceFrameNumber] -> output frame index */
    sourceToOut,
    stills: STILLS.map((s) => ({ ...s, src: `/stills/${s.name}.webp` })),
  }
  await fs.writeFile(path.join(OUT_DIR, 'manifest.json'), JSON.stringify(manifest))

  // Human-readable mapping for the scene config.
  const marks = [1, 68, 69, 99, 100, 147, 148, 188, 189, 243, 244, 256, 257, 300]
  console.log('\nsource frame -> output index')
  console.log(marks.map((m) => `  ${m} -> ${sourceToOut[m]}`).join('\n'))
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
